name: Swift CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  workflow_dispatch:

jobs:
  run-ci:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build --enable-code-coverage --build-path .build/coverage-build
    - name: Run tests
      run: swift test --enable-code-coverage --build-path .build/coverage-build
